version: '3'


services:
  web:
    build: ./.docker/php-fpm
    volumes:
      - ./:/var/www/app
    # environment:
      # DB_HOST: 127.0.0.1
      # DB_PORT: 3306
  nginx:
    image: nginx
    volumes:
     - ./:/var/www/app
     - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8000:80"
    environment:
     - NGINX_HOST=127.0.0.1
     - NGINX_PORT=80
    depends_on:
      - web
  rabbitmq:
    image: rabbitmq
    command: ["rabbitmq-server", "--appendonly", "yes"]
    hostname: rabitmq
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
#    environment:
#      REDIS_HOST: 127.0.0.1
    ports:
      - 6379:6379