version: '3'


services:
  web:
    build: ./.docker/php-fpm
    volumes:
      - ./:/var/www/app
    # environment:
      # DB_HOST: 127.0.0.1
      # DB_PORT: 3306
    depends_on:
      - rabit
  nginx:
    image: nginx
    volumes:
     - ./:/var/www/app
     - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8000:80"
    environment:
     - NGINX_HOST=127.0.0.1
     - NGINX_PORT=80
    depends_on:
      - web
  rabit:
    image: rabbitmq:3.8.0
    command: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    hostname: localrab
